### PR TITLE
Remove Bad Apostrophe from "its flipped reflection."

### PR DESCRIPTION
**Pull request by curtisgibby**
I run a grammar blog at BadApostrophes.com, and unfortunately, I've spotted an unnecessary apostrophe in your Lake.js demo page.  In the description, "and it's flipped reflection" doesn't need an apostrophe.

I've written this up at http://www.badapostrophes.com/2012/04/its-a-trilogy-reflecting-on-mediocrity/ , but I'll be happy to update my post if you merge my change and update the page.

Thanks,
Curtis Gibby
BadApostrophes.com

### CODE REVIEW

**Comment by Alligator** [comment]
thank's for the correction's.

i don't think i've ever seen a pull request for incorrect grammar before, good shout.

**Comment by jnicholls** [comment]
I like how he blackmailed you by threatening to leave the career-ending blog post up with no update if you didn't merge the PR - bullish to say the least

**Comment by ianleckey** [comment]
LOL, speechless!

**Comment by curtisgibby** [comment]
I wouldn't characterize what I did as blackmail.  I already named-and-shamed him on the Bad Apostrophes blog, and that entry stays up, regardless of how he responded to the pull request.  (I did update the blog with an "attaboy" for him removing the errant apostrophe.)  

In the end, my intent was not to put anyone down, but to increase awareness of correct grammar.  If that means me looking like a grammar nerd on the Internet, so be it.  I'm guessing that Reese (and Jarred) will think twice the next time he's about to add an apostrophe to "it's" -- "Is this one of those cases where I'm supposed to use an apostrophe or not?"  That's my goal.

How about an amusing lesson from The Oatmeal? http://theoatmeal.com/comics/apostrophe

**Comment by ianleckey** [comment]
By all means criticise his code, but this isn't really the environment to go around waving a grammar sword. In short, jog on.

**Comment by curtisgibby** [comment]
I think anyplace, including GitHub, is an appropriate forum to talk grammar, especially since programmers seem to have more of a problem with correct punctuation, as evidenced by the ton of bad examples at http://www.badapostrophes.com/tag/programmers/ (Either that, or I just read more stuff written by programmers and therefore find more BAs in their writing.)

**Comment by ianleckey** [comment]
Or, you're just using this as a way of generating traffic for your blog? Not sure. By all means, criticise those whose profession is reliant on excellent grammar. No qualms with that. But not here. It's like complaining that a Spanish waiter can't pronounce a word correctly. Ultimately you understood and it is irrelevant to the meal/drink you ordered.

**Pull request merged**
